#!/bin/bash
# vim: ft=sh

if [[ $OSTYPE == "linux-gnu" ]]; then
    alias gdb='gdb -q'
    alias dstat='dstat -cdlmnpsy'
    alias release_memory='sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"'
    alias open="xdg-open"
    alias pbcopy='xsel --clipboard --input'
    alias pbpaste='xsel --clipboard --output'
fi

if [[ $OSTYPE == "darwin"* ]] || [[ $OSTYPE == "freebsd"* ]]; then
    if [[ $OSTYPE == "darwin"* ]]; then
        alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
        alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
        alias my_installed_app='mdfind kMDItemContentTypeTree=com.apple.application-bundle -onlyin /'
        alias mv='/bin/mv'
        alias buuc='(echo "brew update" && brew update && echo "brew upgrade" && brew upgrade && echo "brew cleanup" && brew cleanup)'
    fi
fi

# https://askubuntu.com/a/22043/15376
# https://stackoverflow.com/a/257666/528929
alias sudo='sudo env PATH=$PATH '

alias adl="aria2c -s16 -x16"

alias ls='ls -F --color=auto'
alias la='ls -AhF'
alias ll='ls -lhF'
alias l='ls'
alias lrt='ls -lrthF'
alias ldot='ls -ld .*'
alias sl='ls'

alias vi="nvim -u \$HOME/.config/nvim/simple.lua"
alias vim=vi
alias nvimdiff='nvim -d'

alias q='exit'
