#!/bin/bash
# -*- mode: sh -*-
# vim: ft=sh

if [[ $OSTYPE == "linux-gnu" ]]; then

    alias grep='grep --color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn' 
    alias gdb='gdb -q'
    alias dstat='dstat -cdlmnpsy'
    alias release_memory='sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"'
    ## since there are  no .desktop files for them
    alias boogie='mono ~/repos/boogie/boogie/Binaries/Boogie.exe'
    alias idaq='~/idademo65/idaq&'
    alias pycharm='nohup ~/tools/pycharm/bin/pycharm.sh &>/dev/null &'
    alias clion='nohup ~/tools/clion-IDE/bin/clion.sh &>/dev/null &'
    alias intellij='nohup ~/tools/intellij/bin/idea.sh &>/dev/null &'
    alias eclipse='nohup ~/tools/eclipse/eclipse &>/dev/null &'
    alias android-studio='nohup ~/tools/android-studio/bin/studio.sh &>/dev/null &'
    alias goagent="~/tools/goagent/local/goagent-gtk.py &>/dev/null &disown"
    alias open="xdg-open"
    ### personal use
    alias opt='opt -load ~/RESEARCH/yama/RA/src/build/bin/librange.so'
    alias lit='${MY_LLVM_ROOT}/src/utils/lit/lit.py'
    alias pbcopy='xsel --clipboard --input'
    alias pbpaste='xsel --clipboard --output'
    alias my_debian_install='cat /var/log/dpkg.log | grep "\ install\ "|less'
fi

if [[ $OSTYPE == "darwin"* ]] || [[ $OSTYPE == "freebsd"* ]]; then
    if [[ $OSTYPE == "darwin"* ]]; then
        alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
        alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
        alias my_lab="ssh hongxu@155.69.142.46 -t -- /bin/sh -c 'tmux has-session && exec tmux attach || exec tmux'"
        alias my_ubuntu64='cd ~/VirtualBox\ VMs/ubuntu && vagrant up && vagrant ssh --command "tmux"'
        alias my_ubuntu32='cd ~/VirtualBox\ VMs/32ubuntu && vagrant up && vagrant ssh --command "tmux"'
        alias my_installed_app='mdfind kMDItemContentTypeTree=com.apple.application-bundle -onlyin /'
    fi
fi

# GNU-coreutils ls
alias sudo='sudo -H '
# alias scala='command scala -i ~/.scalarc'

alias sss='env JAVA_OPTS="-Xms512m -Xmx2g" scala'

alias r_cp='rsync -poghb --backup-dir=/tmp/rsync -e /dev/null --progress --'
alias r_mv='rsync -a --progress -h --remove-source-files'
alias r_update='rsync -avu --progress -h'
alias r_sync='rsync -avu --delete --progress -h'
alias trash-empty='rm -rf ~/.local/share/Trash'

alias pscpu10='ps -e -o pcpu,cpu,nice,state,cputime,args|sort -k1 -nr | head -10'
alias psmem10='ps -e -orss=,args= | sort -b -k1,1n| head -10'
alias my_paths='echo -e ${PATH//:/\\n}'
alias deleted_files='sudo lsof |grep "\(deleted\)"'

alias sbt='command activator'
alias activator='JAVA_HOME=/usr/lib/jvm/java-8-oracle sbt'
alias pom2sbt='mvn dependency:tree | grep "] +" | perl -pe '"'"'s/.*\s([\w\.\-]+):([\w\.\-]+):\w+:([\w\.\-]+):(\w+).*/libraryDependencies += "$1" % "$2" % "$3" % "$4" /'"'"' >build.sbt'

alias my_py_path='python -c "import sys;print(\"\\n\".join(sys.path))"'
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])"'
alias urldecode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias yaml2json="python -c 'import sys, yaml, json; json.dump(yaml.load(open(sys.argv[1])), sys.stdout, indent=2)'"
alias xml_pretty='xmllint --format'
alias p_httpd='python -m SimpleHTTPServer'
alias p_sh='ipython --profile=sh'
alias p_nb='cd ~/src/ipynb && ipython notebook --profile=nb --no-browser'
alias pprof='google-pprof'
alias grt='cd "$(git rev-parse --show-toplevel)"'
alias indent='command indent -kr -ci2 -cli2 -i2 -l80 -nut' #Google style
alias more='less'
# alias less='colorless'
alias diff='colordiff'
alias svn='colorsvn'
alias info='man'
alias dl='axel -a -n 8 -U "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.6) Gecko/20070725 Firefox/2.0.0.6" -H "Accept:text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5 Accept-Language: en-us,en;q=0.5 Accept-Encoding: gzip,deflate Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7 Keep-Alive: 300"'
alias adl="aria2c -s16 -x16"

alias d_gcc='gcc -E -x c  /dev/null -dM'
alias v_gcc='gcc -E -x c /dev/null -v'
alias d_clang='clang -E -x c  /dev/null -dM'
alias v_clang='clang -E -x c /dev/null -v'
alias d_g++='g++ -E -x c++  /dev/null -dM'
alias v_g++='gcc -E -x c++ /dev/null -v'
alias d_clang++='clang++ -E -x c++  /dev/null -dM'
alias v_clang++='clang++ -E -x c++ /dev/null -v'
alias help_cc1='clang -cc1 -analyzer-checker-help |less'
alias scan_build='scan-build --use-analyzer=$(which clang)'
alias v_cc1_o0='clang /dev/null -xc -O0 - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_o1='clang /dev/null -xc -O1 - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_o2='clang /dev/null -xc -O2 - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_o3='clang /dev/null -xc -O3 - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_os='clang /dev/null -xc -Os - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_oz='clang /dev/null -xc -Oz - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_ofast='clang /dev/null -xc -Ofast - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_clang_llvm='clang -xc /dev/null -c -mllvm -print-all-options'

alias fuck='$(thefuck $(fc -ln -1))'

alias buuc='(echo "brew update" && brew update && echo "brew upgrade" && brew upgrade && echo "brew cleanup" brew cleanup)'

alias rdm_res='tail -f /tmp/rdm_answer'

# alias lab_rdp='rdesktop -g 1024x768 -f -u pub -p 123 -r sound:local -r clipboard:PRIMARYCLIPBOARD -r disk:home=/home/hongxu 192.168.1.108 &>/dev/null & disown'
alias pat_ssh='ssh -X root@pat.sce.ntu.edu.sg'

alias dud='du -d 1 -h'
alias duf='du -sh *'
alias sane_f='find . -type f -print0 | xargs -0 chmod 644'
alias sane_d='find . -type d -print0 | xargs -0 chmod 755'

alias ls='ls -F --color=auto'
alias la='ls -AhF'
alias ll='ls -lhF'
alias l='ls'
alias lrt='ls -lrthF'
alias ldot='ls -ld .*'
alias kl='k.zsh | less'
alias sl='ls'

alias my_node_install='npm install -g'
alias node='env node --harmony --use-strict'

alias deb_latest_installed='cat /var/log/dpkg.log | grep "\ install\ "'

alias vi='vim'
alias v='vim -u ~/.vless'
alias e=vim
alias q='exit'
