#!/bin/bash
# -*- mode: sh -*-
# vim: ft=sh

if [[ $OSTYPE == "linux-gnu" ]]; then
    alias gdb='gdb -q'
    alias dstat='dstat -cdlmnpsy'
    alias release_memory='sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"'
    ## since there are  no .desktop files for them
    alias boogie='mono ~/repos/boogie/boogie/Binaries/Boogie.exe'
    alias idaq='~/idademo65/idaq&'
    alias pycharm='~/tools/pycharm/bin/pycharm.sh &>/dev/null &'
    alias goagent="~/tools/goagent/local/goagent-gtk.py &>/dev/null &disown"
    alias open="xdg-open"
    ### personal use
    alias opt='opt -load ~/RESEARCH/snippets_llvm/build/bin/libsnippets.so -load ~/RESEARCH/marple/build/bin/libmyaa.so'
    alias lit='${MY_LLVM_ROOT}/src/utils/lit/lit.py'
    alias pbcopy='xsel --clipboard --input'
    alias pbpaste='xsel --clipboard --output'
fi

if [[ $OSTYPE == "darwin"* ]] || [[ $OSTYPE == "freebsd"* ]]; then
    # alias ls='ls -G'
    if [[ $OSTYPE == "darwin"* ]]; then
        alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
        alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
        alias my_lab="ssh hongxu@155.69.142.46 -t -- /bin/sh -c 'tmux has-session && exec tmux attach || exec tmux'"
    fi
fi

# GNU-coreutils ls
alias ls='ls --color=tty'

alias r_cp='rsync -poghb --backup-dir=/tmp/rsync -e /dev/null --progress --'
alias r_mv='rsync -a --progress -h --remove-source-files'
alias r_update='rsync -avu --progress -h'
alias r_sync='rsync -avu --delete --progress -h'
alias trash-empty='rm -rf ~/.local/share/Trash'

alias pscpu10='ps -e -o pcpu,cpu,nice,state,cputime,args|sort -k1 -nr | head -10'
alias psmem10='ps -e -orss=,args= | sort -b -k1,1n| head -10'
# alias path='echo -e ${PATH//:/\\n}'

alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])"'
alias urldecode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias xml_pretty='xmllint --format'
alias p_httpd='python -m SimpleHTTPServer'
alias p_sh='ipython --profile=sh'
alias p_nb='cd ~/src/ipynb && ipython notebook --matplotlib inline --profile nb'
alias pprof='google-pprof'
alias grt='cd $(git rev-parse --show-toplevel)'
alias indent='command indent -kr -ci2 -cli2 -i2 -l80 -nut' #Google style
alias more='less'
# alias less='colorless'
alias diff='colordiff'
alias svn='colorsvn'
alias sudo='sudo '
alias info='man'
alias dl='axel -a -n 8 -U "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.6) Gecko/20070725 Firefox/2.0.0.6" -H "Accept:text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5 Accept-Language: en-us,en;q=0.5 Accept-Encoding: gzip,deflate Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7 Keep-Alive: 300"'
alias adl="aria2c -s16 -x16"

alias d_gcc='gcc -E -x c  /dev/null -dM'
alias v_gcc='gcc -E -x c /dev/null -v'
alias d_clang='clang -E -x c  /dev/null -dM'
alias v_clang='clang -E -x c /dev/null -v'
alias d_g++='g++ -E -x c++  /dev/null -dM'
alias v_g++='gcc -E -x c++ /dev/null -v'
alias d_clang++='clang++ -E -x c++  /dev/null -dM'
alias v_clang++='clang++ -E -x c++ /dev/null -v'
alias help_cc1='clang -cc1 -analyzer-checker-help |less'
alias scan_build='scan-build --use-analyzer=$(which clang)'
alias v_cc1_o0='clang /dev/null -xc -O0 - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_o1='clang /dev/null -xc -O1 - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_o2='clang /dev/null -xc -O2 - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_o3='clang /dev/null -xc -O3 - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_os='clang /dev/null -xc -Os - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_oz='clang /dev/null -xc -Oz - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_cc1_ofast='clang /dev/null -xc -Ofast - -o /dev/null -\#\#\# 2>&1 | tr " " "\n"'
alias v_clang_llvm='clang -xc /dev/null -c -mllvm -print-all-options'

alias buuc='echo "brew update" && brew update && echo "brew upgrade" && brew upgrade && "brew cleanup" brew cleanup'

alias rdm_res='tail -f /tmp/rdm_answer'

# alias lab_rdp='rdesktop -g 1024x768 -f -u pub -p 123 -r sound:local -r clipboard:PRIMARYCLIPBOARD -r disk:home=/home/hongxu 192.168.1.108 &>/dev/null & disown'
alias pat_ssh='ssh -X root@pat.sce.ntu.edu.sg'

alias dud='du -d 1 -h'
alias duf='du -sh *'
alias fd='find . -type d -name'
alias ff='find . -type f -name'

alias la='ls -Ah'
alias l='ls -F'
alias ll='ls -lh'
alias lrt='ls -lrth'
alias ldot='ls -ld .*'
alias kl='k.zsh | less'
alias sl='ls'

alias vi='vim'
alias v='vim -u ~/.vless'
alias e=vim
alias q='exit'
