#!/usr/bin/env python

import os
import shlex
import subprocess
import sys

rootdir_cmd = shlex.split("git rev-parse --show-toplevel")
try:
    cwd = subprocess.check_output(rootdir_cmd, text=True).strip()
    print(cwd)
    os.chdir(cwd)
except subprocess.CalledProcessError as e:
    sys.exit(e.stderr)

cmds = ["git stash", "git pull", "git stash pop"]
for cmd in cmds:
    cmd_list = shlex.split(cmd)
    print(cmd)
    subprocess.call(cmd_list)
