(require 'eclim)
(require 'eclimd)
(global-eclim-mode t)
(setq eclim-eclipse-dirs "~/data_backup/eclipse")
(setq eclimd-executable "~/data_backup/eclipse/eclimd")
(setq eclim-executable "~/data_backup/eclipse/eclim")
(setq help-at-pt-display-when-idle t)
(setq help-at-pt-timer-delay 0.1)
(help-at-pt-set-timer)
(require 'ac-emacs-eclim-source)
(ac-emacs-eclim-config)
(provide 'init-eclim)
